trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    sudo apt-get update
    sudo apt-get install -y build-essential gcovr
  displayName: 'Install GCC and gcovr'

- script: |
    make coverage
  displayName: 'Run Unit Tests and Generate Coverage Report'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'coverage.html'
    ArtifactName: 'CoverageReport'
    publishLocation: 'Container'
  condition: succeededOrFailed()
