/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	//LED is connected to PB14
	uint32_t *pclk= (uint32_t*) 0x40023830;// this is the address rcc reg for AHB1
	uint32_t *pGPIO_mode=(uint32_t*)0x40020400;// address of MODER reg of gpio
	uint32_t *pGPIO_op=(uint32_t*)0x40020414;// address of output reg of port b


	*pclk=*pclk|(1<<1);// setting up rcc for GPIO B

	*pGPIO_mode=*pGPIO_mode &~(3 << (28));//Resetting MODER reg for port B
	*pGPIO_mode=*pGPIO_mode |(1<<28);//Setting MODER reg for port B

	*pGPIO_op=*pGPIO_op|(1<<14);// Setting 14th pin of port B

    while (1){

    	*pGPIO_op ^=(1<<14); //toggeling 14th pin of port b
    	for ( uint32_t i = 0; i < 150000; ++i);

    }
}
